export type TriageNode = {
  id: string;
  question: string;
  yes: string | null;
  no: string | null;
  isLeaf: boolean;
  treatment: string;
  severity: 'green' | 'yellow' | 'red';
  steps: string[];
  escalate?: string[];
};

export const TRIAGE_ROOT = 'start';

export const TRIAGE_TREE: Record<string, TriageNode> = {
  start: {
    id: 'start',
    question: 'Is the person awake and breathing normally?',
    yes: 'bleeding',
    no: 'airway',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  airway: {
    id: 'airway',
    question: 'After opening the airway (head tilt/chin lift), are they breathing?',
    yes: 'recovery',
    no: 'cpr',
    isLeaf: false,
    treatment: '',
    severity: 'red',
    steps: [],
  },
  cpr: {
    id: 'cpr',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'No normal breathing',
    severity: 'red',
    steps: [
      'Call for help immediately',
      'Start chest compressions hard and fast at 100-120/min',
      'Give 30 compressions then 2 rescue breaths if trained',
      'Use AED as soon as available and follow prompts',
    ],
    escalate: ['Not breathing or gasping', 'No pulse felt', 'No AED available within minutes'],
  },
  recovery: {
    id: 'recovery',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Unconscious but breathing',
    severity: 'yellow',
    steps: ['Place in recovery position', 'Keep airway clear', 'Monitor breathing continuously', 'Call for help'],
  },
  bleeding: {
    id: 'bleeding',
    question: 'Is there heavy or spurting bleeding?',
    yes: 'heavyBleedingLeaf',
    no: 'chestStroke',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  heavyBleedingLeaf: {
    id: 'heavyBleedingLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Severe hemorrhage',
    severity: 'red',
    steps: [
      'Call for help now',
      'Apply firm direct pressure with cloth/gauze',
      'Pack wound deeply if possible',
      'Apply tourniquet above limb wound if bleeding persists',
      'If limb amputated, wrap part in clean cloth, bag, cool (not on ice)',
      'Keep patient lying flat; watch for shock (pale, sweaty, fast pulse)',
    ],
    escalate: ['Bleeding does not stop with pressure', 'Amputation or partial amputation', 'Signs of shock appear'],
  },
  chestStroke: {
    id: 'chestStroke',
    question: 'Chest pain or stroke signs (face droop, slurred speech, weak arm)?',
    yes: 'chestStrokeLeaf',
    no: 'choking',
    isLeaf: false,
    treatment: '',
    severity: 'red',
    steps: [],
  },
  chestStrokeLeaf: {
    id: 'chestStrokeLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Possible heart attack or stroke',
    severity: 'red',
    steps: [
      'Call for emergency help immediately',
      'Have them chew adult aspirin if not allergic/contraindicated',
      'Sit them upright, loosen tight clothing',
      'If stroke signs, keep airway clear and note time symptoms started',
    ],
    escalate: ['Chest pressure > 5 minutes', 'Stroke signs (FAST test positive)', 'Breathlessness with chest pain'],
  },
  choking: {
    id: 'choking',
    question: 'Are they choking (cannot speak/cough, silent, clutching throat)?',
    yes: 'chokingLeaf',
    no: 'seizureCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  chokingLeaf: {
    id: 'chokingLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Airway obstruction',
    severity: 'red',
    steps: [
      'Give 5 back blows between shoulder blades',
      'Give 5 abdominal thrusts (Heimlich) for adults/children',
      'Alternate 5 back blows and 5 thrusts until cleared or they collapse',
      'If unconscious, start CPR and check mouth for object each cycle',
    ],
    escalate: ['Object not cleared after cycles', 'Turns blue or silent', 'Becomes unconscious'],
  },
  seizureCheck: {
    id: 'seizureCheck',
    question: 'Did they have a seizure or convulsions?',
    yes: 'seizureLeaf',
    no: 'spineTrauma',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  seizureLeaf: {
    id: 'seizureLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Active or recent seizure',
    severity: 'yellow',
    steps: [
      'Protect head with soft padding; clear objects nearby',
      'Do not hold them down or put anything in the mouth',
      'After seizure, place in recovery position once breathing is normal',
      'Time the event; seek help if first seizure, >5 minutes, or repeat',
    ],
    escalate: ['Seizure > 5 minutes', 'Second seizure without regaining consciousness', 'Injury during seizure'],
  },
  spineTrauma: {
    id: 'spineTrauma',
    question: 'Major fall, vehicle crash, or neck/back pain/numbness?',
    yes: 'spineLeaf',
    no: 'fractureCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  spineLeaf: {
    id: 'spineLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Possible spine or head injury',
    severity: 'red',
    steps: [
      'Do not move the neck/back; keep head aligned',
      'Support head with hands or padding',
      'Control bleeding without moving the spine',
      'Monitor breathing; prepare to roll as a unit if vomiting',
    ],
    escalate: ['Any loss of consciousness', 'Weakness/numbness/tingling in limbs', 'Severe head or neck pain'],
  },
  fractureCheck: {
    id: 'fractureCheck',
    question: 'Obvious broken bone or dislocation?',
    yes: 'fractureLeaf',
    no: 'burns',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  fractureLeaf: {
    id: 'fractureLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Suspected fracture/dislocation',
    severity: 'yellow',
    steps: [
      'Immobilize joint above and below injury',
      'Do not straighten deformities; splint as found',
      'Check circulation beyond injury; loosen if numbness increases',
      'Elevate if no spinal risk and ice around (not directly on) the site',
      'If open fracture, cover bone ends with moist sterile dressing',
    ],
    escalate: ['Open fracture or severe deformity', 'No pulse or color below injury', 'Severe pain not relieved by immobilization'],
  },
  burns: {
    id: 'burns',
    question: 'Significant burns, electrical, or chemical exposure?',
    yes: 'burnLeaf',
    no: 'allergyCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  burnLeaf: {
    id: 'burnLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Burn or corrosive injury',
    severity: 'red',
    steps: [
      'Cool thermal burns with clean cool water for 20 minutes (not ice)',
      'Remove jewelry/tight items before swelling',
      'Cover with loose, clean, non-fluffy dressing',
      'For chemicals: brush off dry, then flush with water 20 minutes',
      'For electrical: ensure power off before touching patient; monitor heart',
      'For eye splash: rinse eye with clean water for 15+ minutes, cover lightly',
    ],
    escalate: ['Burns to face, hands, groin, or large area', 'Electrical or chemical burns', 'Signs of airway burn (soot, hoarse voice)'],
  },
  allergyCheck: {
    id: 'allergyCheck',
    question: 'Severe allergy signs (swollen lips/tongue, trouble breathing)?',
    yes: 'anaphylaxisLeaf',
    no: 'asthmaCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  asthmaCheck: {
    id: 'asthmaCheck',
    question: 'Asthma attack or wheezing with breathlessness?',
    yes: 'asthmaLeaf',
    no: 'shockCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  asthmaLeaf: {
    id: 'asthmaLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Breathing difficulty/asthma',
    severity: 'red',
    steps: [
      'Sit them upright and keep calm',
      'Use reliever inhaler: 4 puffs via spacer (1 puff, 4 breaths), repeat every 4 minutes',
      'If no spacer, 1-2 puffs directly, repeat as above',
      'If not improving after 3 cycles or getting worse, call for emergency help',
    ],
    escalate: ['No improvement after 3 cycles of reliever', 'Blue/grey lips or fingernails', 'Too breathless to speak full sentences'],
  },
  anaphylaxisLeaf: {
    id: 'anaphylaxisLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Severe allergic reaction',
    severity: 'red',
    steps: [
      'Use epinephrine auto-injector immediately if available',
      'Have them sit up if breathing is hard, or lie down if dizzy',
      'Give second epinephrine after 5-10 minutes if symptoms persist and available',
      'Call for emergency help and monitor airway',
    ],
    escalate: ['Any breathing difficulty with swelling', 'No response to first epinephrine in 5-10 minutes'],
  },
  shockCheck: {
    id: 'shockCheck',
    question: 'Signs of shock (pale/clammy skin, fast weak pulse, confusion)?',
    yes: 'shockLeaf',
    no: 'heatCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  shockLeaf: {
    id: 'shockLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Treating shock',
    severity: 'red',
    steps: [
      'Lay the person flat; elevate legs if no injury forbids',
      'Keep warm with blankets',
      'Stop visible bleeding',
      'Do not give food/drink if unconscious or surgery likely',
      'Reassure and monitor breathing',
      'If available, give oxygen per protocol',
    ],
    escalate: ['Weak or worsening pulse', 'Mental status declining', 'Continued bleeding despite pressure'],
  },
  heatCheck: {
    id: 'heatCheck',
    question: 'Heat illness signs (hot dry skin, confusion, cramps)?',
    yes: 'heatLeaf',
    no: 'coldCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  heatLeaf: {
    id: 'heatLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Heat exhaustion/stroke care',
    severity: 'red',
    steps: [
      'Move to shade/cool area; remove excess clothing',
      'Cool rapidly: wet cloths, fan, ice packs to neck/armpits/groin',
      'If awake, give small sips of cool water',
      'Call for help if confused, seizures, or no improvement',
    ],
    escalate: ['Confusion, seizure, or collapse', 'No improvement after cooling', 'Very high temperature with hot dry skin'],
  },
  coldCheck: {
    id: 'coldCheck',
    question: 'Very cold, shivering stopped, or confused?',
    yes: 'hypothermiaLeaf',
    no: 'dehydrationCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  hypothermiaLeaf: {
    id: 'hypothermiaLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Hypothermia care',
    severity: 'red',
    steps: [
      'Move to shelter; remove wet clothing gently',
      'Warm slowly with dry layers and body heat',
      'Give warm sweet drinks if awake; no alcohol',
      'Handle gently; avoid sudden movements',
    ],
    escalate: ['Stops shivering, becomes drowsy or confused', 'Stiffness or slowed breathing'],
  },
  dehydrationCheck: {
    id: 'dehydrationCheck',
    question: 'Vomiting/diarrhea and cannot keep fluids down?',
    yes: 'dehydrationLeaf',
    no: 'diabetesCheck',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  dehydrationLeaf: {
    id: 'dehydrationLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Dehydration/GI illness',
    severity: 'yellow',
    steps: [
      'Give oral rehydration solution in small frequent sips',
      'Stop if vomiting worsens; let stomach rest briefly then retry',
      'Monitor for dizziness or reduced urine',
      'Seek help if blood in vomit/stool or unable to keep fluids for 6+ hours',
    ],
    escalate: ['Blood in vomit or stool', 'No urine for 8 hours', 'Persistent vomiting despite pauses'],
  },
  diabetesCheck: {
    id: 'diabetesCheck',
    question: 'Known diabetes with confusion, shaking, or sweating?',
    yes: 'diabetesLeaf',
    no: 'minorLeaf',
    isLeaf: false,
    treatment: '',
    severity: 'yellow',
    steps: [],
  },
  diabetesLeaf: {
    id: 'diabetesLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Possible low blood sugar (hypoglycemia)',
    severity: 'yellow',
    steps: [
      'If awake and can swallow, give fast sugar: glucose tabs/gel, juice, or candy',
      'Follow with slow carbs (bread/crackers) if available',
      'If unconscious or cannot swallow, do not give food/drink; place in recovery position',
      'Seek help if no improvement in 10 minutes or they become drowsy/unconscious',
    ],
    escalate: ['No improvement after sugar in 10 minutes', 'Unconscious or cannot swallow'],
  },
  minorLeaf: {
    id: 'minorLeaf',
    question: '',
    yes: null,
    no: null,
    isLeaf: true,
    treatment: 'Likely minor/monitor',
    severity: 'green',
    steps: ['Clean small wounds', 'Rest, hydrate, reassess every 15 minutes', 'If pain/swelling worsens, re-triage'],
  },
};
